spring:

## 默认数据源配置
  datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password:
      driverClassName: com.mysql.jdbc.Driver
      initial-size: 0                                               # 初始化连接大小
      max-active: 20                                                # 连接池最大使用连接数量
      max-idle: 20                                                  # 连接池最大空闲
      min-idle: 0                                                   # 连接池最小空闲
      max-wait: 60000                                               # 获取连接最大等待时间
  jpa:
      database: mysql
      generate-ddl: false
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
